// <auto-generated />
using System;
using GalacticTrader.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GalacticTrader.Data.Migrations
{
    [DbContext(typeof(GalacticTraderDbContext))]
    partial class GalacticTraderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GalacticTrader.Data.Models.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValuePerUnit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("ShipId");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.ChannelMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsModerated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("ChannelType", "ChannelKey", "CreatedAt");

                    b.ToTable("ChannelMessages");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.CombatLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttackerDamageDealt")
                        .HasColumnType("integer");

                    b.Property<int>("AttackerHullDamage")
                        .HasColumnType("integer");

                    b.Property<Guid>("AttackerId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttackerInitialRating")
                        .HasColumnType("integer");

                    b.Property<int>("AttackerReputationChange")
                        .HasColumnType("integer");

                    b.Property<decimal>("AttackerReward")
                        .HasColumnType("numeric");

                    b.Property<Guid>("AttackerShipId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BattleEndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BattleOutcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BattleStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DefenderCompensation")
                        .HasColumnType("numeric");

                    b.Property<int>("DefenderDamageDealt")
                        .HasColumnType("integer");

                    b.Property<int>("DefenderHullDamage")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DefenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("DefenderInitialRating")
                        .HasColumnType("integer");

                    b.Property<int>("DefenderReputationChange")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DefenderShipId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal>("InsurancePayout")
                        .HasColumnType("numeric");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationSectorId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalTicks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttackerShipId");

                    b.HasIndex("DefenderId");

                    b.HasIndex("DefenderShipId");

                    b.HasIndex("LocationId");

                    b.HasIndex("AttackerId", "BattleStartedAt");

                    b.ToTable("CombatLogs");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Commodity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("BasePrice")
                        .HasColumnType("real");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("LegalityFactor")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Rarity")
                        .HasColumnType("real");

                    b.Property<float>("Volume")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Commodities");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.CorporateWar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttackerFactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CasusBelli")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DefenderFactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Intensity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttackerFactionId");

                    b.HasIndex("DefenderFactionId");

                    b.HasIndex("IsActive", "StartedAt");

                    b.ToTable("CorporateWars");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Crew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CombatSkill")
                        .HasColumnType("integer");

                    b.Property<int>("EngineeringSkill")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("integer");

                    b.Property<long>("ExperiencePoints")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Loyalty")
                        .HasColumnType("integer");

                    b.Property<int>("Morale")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NavigationSkill")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ShipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ShipId");

                    b.ToTable("Crew");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Faction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlignmentBias")
                        .HasColumnType("integer");

                    b.Property<int>("ControlledSectors")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("InfluenceScore")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("PowerScore")
                        .HasColumnType("real");

                    b.Property<int>("ReputationDecayPerDay")
                        .HasColumnType("integer");

                    b.Property<double>("ReputationMultiplier")
                        .HasColumnType("double precision");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TradeGoodModifier")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TreasuryBalance")
                        .HasColumnType("numeric");

                    b.Property<float>("WealthScore")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.InfrastructureOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("ControlScore")
                        .HasColumnType("real");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("InfrastructureType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("SectorId", "InfrastructureType")
                        .IsUnique();

                    b.ToTable("InfrastructureOwnerships");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.InsuranceClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CombatLogId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FiledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("FraudRiskScore")
                        .HasColumnType("real");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CombatLogId");

                    b.HasIndex("PolicyId", "FiledAt");

                    b.ToTable("InsuranceClaims");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.InsurancePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("CoverageRate")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastPremiumChargedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PremiumPerCycle")
                        .HasColumnType("numeric");

                    b.Property<string>("RiskTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShipId")
                        .IsUnique();

                    b.HasIndex("PlayerId", "IsActive");

                    b.ToTable("InsurancePolicies");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.IntelligenceNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetCount")
                        .HasColumnType("integer");

                    b.Property<float>("CoverageScore")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerPlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerPlayerId", "Name")
                        .IsUnique();

                    b.ToTable("IntelligenceNetworks");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.IntelligenceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("real");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NetworkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("NetworkId", "SectorId", "DetectedAt");

                    b.ToTable("IntelligenceReports");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Leaderboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaderboardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PreviousScore")
                        .HasColumnType("numeric");

                    b.Property<long>("Rank")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("LeaderboardType", "Rank");

                    b.ToTable("Leaderboards");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.MarketListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AvailableQuantity")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric");

                    b.Property<float>("DemandMultiplier")
                        .HasColumnType("real");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<long>("MaxQuantity")
                        .HasColumnType("bigint");

                    b.Property<long>("MinQuantity")
                        .HasColumnType("bigint");

                    b.Property<float>("PriceChangePercent24h")
                        .HasColumnType("real");

                    b.Property<DateTime>("PriceLastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("RiskPremium")
                        .HasColumnType("real");

                    b.Property<float>("ScarcityModifier")
                        .HasColumnType("real");

                    b.Property<long>("TotalTradeVolume24h")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("MarketId");

                    b.ToTable("MarketListings");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.MarketPriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MarketListingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("VolumeTraded")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MarketListingId", "RecordedAt");

                    b.ToTable("MarketPriceHistories");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.NPCAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AggressionIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Archetype")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentGoal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CurrentLocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("DecisionTick")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("FleetSize")
                        .HasColumnType("integer");

                    b.Property<float>("InfluenceScore")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReputationScore")
                        .HasColumnType("integer");

                    b.Property<float>("RiskTolerance")
                        .HasColumnType("real");

                    b.Property<Guid?>("TargetLocationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TradeVolume24h")
                        .HasColumnType("numeric");

                    b.Property<bool>("TradesIllegally")
                        .HasColumnType("boolean");

                    b.Property<bool>("TradesLegally")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Wealth")
                        .HasColumnType("numeric");

                    b.Property<float>("WealthTarget")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("FactionId");

                    b.HasIndex("TargetLocationId");

                    b.ToTable("NPCAgents");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.NPCShip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CombatRating")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CurrentSectorId")
                        .HasColumnType("uuid");

                    b.Property<int>("HullIntegrity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxHullIntegrity")
                        .HasColumnType("integer");

                    b.Property<Guid>("NPCAgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSectorId");

                    b.HasIndex("NPCAgentId");

                    b.ToTable("NPCShips");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlignmentLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FleetStrengthRating")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KeycloakUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LiquidCredits")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetWorth")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProtectionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReputationScore")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakUserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.PlayerFactionRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasAccess")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReputationScore")
                        .HasColumnType("integer");

                    b.Property<decimal>("TradingDiscount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("PlayerId", "FactionId")
                        .IsUnique();

                    b.ToTable("PlayerFactionRelationships");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("BaseRiskScore")
                        .HasColumnType("real");

                    b.Property<Guid>("FromSectorId")
                        .HasColumnType("uuid");

                    b.Property<float>("FuelCost")
                        .HasColumnType("real");

                    b.Property<bool>("HasAnomalies")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDiscovered")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToSectorId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrafficIntensity")
                        .HasColumnType("integer");

                    b.Property<int>("TravelTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<float>("VisibilityRating")
                        .HasColumnType("real");

                    b.Property<string>("WarpGateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FromSectorId");

                    b.HasIndex("ToSectorId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AverageTrafficLevel")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ControlledByFactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("EconomicIndex")
                        .HasColumnType("integer");

                    b.Property<int>("HazardRating")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PiratePresenceProbability")
                        .HasColumnType("integer");

                    b.Property<float>("ResourceModifier")
                        .HasColumnType("real");

                    b.Property<int>("SecurityLevel")
                        .HasColumnType("integer");

                    b.Property<float>("SensorInterferenceLevel")
                        .HasColumnType("real");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.Property<float>("Z")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ControlledByFactionId");

                    b.HasIndex("Name");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.SectorVolatilityCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CycleStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextTransitionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid");

                    b.Property<float>("VolatilityIndex")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SectorId", "LastUpdatedAt");

                    b.ToTable("SectorVolatilityCycles");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CargoCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("CargoUsed")
                        .HasColumnType("integer");

                    b.Property<int>("CrewSlots")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CurrentSectorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("numeric");

                    b.Property<int>("Hardpoints")
                        .HasColumnType("integer");

                    b.Property<bool>("HasInsurance")
                        .HasColumnType("boolean");

                    b.Property<int>("HullIntegrity")
                        .HasColumnType("integer");

                    b.Property<decimal>("InsuranceRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInCombat")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxHullIntegrity")
                        .HasColumnType("integer");

                    b.Property<int>("MaxShieldCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReactorOutput")
                        .HasColumnType("integer");

                    b.Property<int>("SensorRange")
                        .HasColumnType("integer");

                    b.Property<int>("ShieldCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("ShipClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SignatureProfile")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetSectorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSectorId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TargetSectorId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.ShipModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxHealthPoints")
                        .HasColumnType("integer");

                    b.Property<string>("ModuleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipModules");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.TerritoryDominance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ControlledSectorCount")
                        .HasColumnType("integer");

                    b.Property<float>("DominanceScore")
                        .HasColumnType("real");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<float>("InfrastructureControlScore")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("WarMomentumScore")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FactionId")
                        .IsUnique();

                    b.ToTable("TerritoryDominances");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.TradeTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromMarketId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InsuranceCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetProfit")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("numeric");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Tariff")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ToMarketId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TransactionFee")
                        .HasColumnType("numeric");

                    b.Property<bool>("UsedSmugglingRoute")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("FromMarketId");

                    b.HasIndex("ToMarketId");

                    b.HasIndex("PlayerId", "CreatedAt");

                    b.ToTable("TradeTransactions");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KeycloakId")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Cargo", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Commodity", "Commodity")
                        .WithMany("Cargo")
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Ship", "Ship")
                        .WithMany("Cargo")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commodity");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.ChannelMessage", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Player", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.CombatLog", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Player", "Attacker")
                        .WithMany("CombatLogs")
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Ship", "AttackerShip")
                        .WithMany()
                        .HasForeignKey("AttackerShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Player", "Defender")
                        .WithMany()
                        .HasForeignKey("DefenderId");

                    b.HasOne("GalacticTrader.Data.Models.Ship", "DefenderShip")
                        .WithMany()
                        .HasForeignKey("DefenderShipId");

                    b.HasOne("GalacticTrader.Data.Models.Sector", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attacker");

                    b.Navigation("AttackerShip");

                    b.Navigation("Defender");

                    b.Navigation("DefenderShip");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.CorporateWar", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Faction", "AttackerFaction")
                        .WithMany()
                        .HasForeignKey("AttackerFactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Faction", "DefenderFaction")
                        .WithMany()
                        .HasForeignKey("DefenderFactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttackerFaction");

                    b.Navigation("DefenderFaction");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Crew", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Player", "Player")
                        .WithMany("Crew")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Ship", "Ship")
                        .WithMany("Crew")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.InfrastructureOwnership", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.InsuranceClaim", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.CombatLog", "CombatLog")
                        .WithMany()
                        .HasForeignKey("CombatLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GalacticTrader.Data.Models.InsurancePolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CombatLog");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.InsurancePolicy", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Ship", "Ship")
                        .WithMany()
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.IntelligenceNetwork", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Player", "OwnerPlayer")
                        .WithMany()
                        .HasForeignKey("OwnerPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerPlayer");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.IntelligenceReport", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.IntelligenceNetwork", "Network")
                        .WithMany("Reports")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Leaderboard", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Market", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Sector", "Sector")
                        .WithMany("Markets")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.MarketListing", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Commodity", "Commodity")
                        .WithMany("MarketListings")
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Market", "Market")
                        .WithMany("Listings")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commodity");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.MarketPriceHistory", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.MarketListing", "MarketListing")
                        .WithMany("PriceHistory")
                        .HasForeignKey("MarketListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketListing");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.NPCAgent", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Sector", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId");

                    b.HasOne("GalacticTrader.Data.Models.Faction", "Faction")
                        .WithMany("Members")
                        .HasForeignKey("FactionId");

                    b.HasOne("GalacticTrader.Data.Models.Sector", "TargetLocation")
                        .WithMany()
                        .HasForeignKey("TargetLocationId");

                    b.Navigation("CurrentLocation");

                    b.Navigation("Faction");

                    b.Navigation("TargetLocation");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.NPCShip", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Sector", "CurrentSector")
                        .WithMany()
                        .HasForeignKey("CurrentSectorId");

                    b.HasOne("GalacticTrader.Data.Models.NPCAgent", "Agent")
                        .WithMany("Ships")
                        .HasForeignKey("NPCAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("CurrentSector");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.PlayerFactionRelationship", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Faction", "Faction")
                        .WithMany("PlayerRelationships")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Player", "Player")
                        .WithMany("FactionRelationships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Route", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Sector", "FromSector")
                        .WithMany("OutboundRoutes")
                        .HasForeignKey("FromSectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Sector", "ToSector")
                        .WithMany("InboundRoutes")
                        .HasForeignKey("ToSectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromSector");

                    b.Navigation("ToSector");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Sector", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Faction", "ControlledByFaction")
                        .WithMany("ControlledSectors_Nav")
                        .HasForeignKey("ControlledByFactionId");

                    b.Navigation("ControlledByFaction");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.SectorVolatilityCycle", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Ship", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Sector", "CurrentSector")
                        .WithMany("DockedShips")
                        .HasForeignKey("CurrentSectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GalacticTrader.Data.Models.Player", "Player")
                        .WithMany("Ships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Sector", "TargetSector")
                        .WithMany()
                        .HasForeignKey("TargetSectorId");

                    b.Navigation("CurrentSector");

                    b.Navigation("Player");

                    b.Navigation("TargetSector");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.ShipModule", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Ship", "Ship")
                        .WithMany("Modules")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.TerritoryDominance", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.TradeTransaction", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Commodity", "Commodity")
                        .WithMany()
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Market", "FromMarket")
                        .WithMany()
                        .HasForeignKey("FromMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Player", "Buyer")
                        .WithMany("TradeTransactions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GalacticTrader.Data.Models.Market", "ToMarket")
                        .WithMany()
                        .HasForeignKey("ToMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Commodity");

                    b.Navigation("FromMarket");

                    b.Navigation("ToMarket");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.UserAccount", b =>
                {
                    b.HasOne("GalacticTrader.Data.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Commodity", b =>
                {
                    b.Navigation("Cargo");

                    b.Navigation("MarketListings");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Faction", b =>
                {
                    b.Navigation("ControlledSectors_Nav");

                    b.Navigation("Members");

                    b.Navigation("PlayerRelationships");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.IntelligenceNetwork", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Market", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.MarketListing", b =>
                {
                    b.Navigation("PriceHistory");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.NPCAgent", b =>
                {
                    b.Navigation("Ships");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Player", b =>
                {
                    b.Navigation("CombatLogs");

                    b.Navigation("Crew");

                    b.Navigation("FactionRelationships");

                    b.Navigation("Ships");

                    b.Navigation("TradeTransactions");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Sector", b =>
                {
                    b.Navigation("DockedShips");

                    b.Navigation("InboundRoutes");

                    b.Navigation("Markets");

                    b.Navigation("OutboundRoutes");
                });

            modelBuilder.Entity("GalacticTrader.Data.Models.Ship", b =>
                {
                    b.Navigation("Cargo");

                    b.Navigation("Crew");

                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
